/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ContractRegistry {
  export type ContractDataStruct = {
    contractHash: string;
    initiator: AddressLike;
    counterparty: AddressLike;
    initiatorSigned: boolean;
    counterpartySigned: boolean;
    createdAt: BigNumberish;
    exists: boolean;
  };

  export type ContractDataStructOutput = [
    contractHash: string,
    initiator: string,
    counterparty: string,
    initiatorSigned: boolean,
    counterpartySigned: boolean,
    createdAt: bigint,
    exists: boolean
  ] & {
    contractHash: string;
    initiator: string;
    counterparty: string;
    initiatorSigned: boolean;
    counterpartySigned: boolean;
    createdAt: bigint;
    exists: boolean;
  };
}

export interface ContractRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contracts"
      | "getContract"
      | "registerContract"
      | "signContract"
      | "userContracts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ContractRegistered" | "ContractSigned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "contracts", values: [string]): string;
  encodeFunctionData(functionFragment: "getContract", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userContracts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userContracts",
    data: BytesLike
  ): Result;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    id: string,
    initiator: AddressLike,
    counterparty: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    initiator: string,
    counterparty: string
  ];
  export interface OutputObject {
    id: string;
    initiator: string;
    counterparty: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractSignedEvent {
  export type InputTuple = [id: string, signer: AddressLike];
  export type OutputTuple = [id: string, signer: string];
  export interface OutputObject {
    id: string;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContractRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ContractRegistry;
  waitForDeployment(): Promise<this>;

  interface: ContractRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contracts: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, boolean, bigint, boolean] & {
        contractHash: string;
        initiator: string;
        counterparty: string;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getContract: TypedContractMethod<
    [_id: string],
    [ContractRegistry.ContractDataStructOutput],
    "view"
  >;

  registerContract: TypedContractMethod<
    [_id: string, _hash: string, _counterparty: AddressLike],
    [void],
    "nonpayable"
  >;

  signContract: TypedContractMethod<[_id: string], [void], "nonpayable">;

  userContracts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean, boolean, bigint, boolean] & {
        contractHash: string;
        initiator: string;
        counterparty: string;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [_id: string],
    [ContractRegistry.ContractDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [_id: string, _hash: string, _counterparty: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signContract"
  ): TypedContractMethod<[_id: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userContracts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContractSigned"
  ): TypedContractEvent<
    ContractSignedEvent.InputTuple,
    ContractSignedEvent.OutputTuple,
    ContractSignedEvent.OutputObject
  >;

  filters: {
    "ContractRegistered(string,address,address)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "ContractSigned(string,address)": TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;
    ContractSigned: TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;
  };
}
