/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ContractRegistry {
  export type ContractDataStruct = {
    contractHash: string;
    initiator: AddressLike;
    counterparty: AddressLike;
    initiatorAmount: BigNumberish;
    counterpartyAmount: BigNumberish;
    initiatorSigned: boolean;
    counterpartySigned: boolean;
    initiatorPaid: boolean;
    counterpartyPaid: boolean;
    createdAt: BigNumberish;
    exists: boolean;
  };

  export type ContractDataStructOutput = [
    contractHash: string,
    initiator: string,
    counterparty: string,
    initiatorAmount: bigint,
    counterpartyAmount: bigint,
    initiatorSigned: boolean,
    counterpartySigned: boolean,
    initiatorPaid: boolean,
    counterpartyPaid: boolean,
    createdAt: bigint,
    exists: boolean
  ] & {
    contractHash: string;
    initiator: string;
    counterparty: string;
    initiatorAmount: bigint;
    counterpartyAmount: bigint;
    initiatorSigned: boolean;
    counterpartySigned: boolean;
    initiatorPaid: boolean;
    counterpartyPaid: boolean;
    createdAt: bigint;
    exists: boolean;
  };
}

export interface ContractRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "contracts"
      | "getContract"
      | "isFullyPaid"
      | "makePayment"
      | "registerContract"
      | "signContract"
      | "userContracts"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractCompleted"
      | "ContractRegistered"
      | "ContractSigned"
      | "PaymentMade"
  ): EventFragment;

  encodeFunctionData(functionFragment: "contracts", values: [string]): string;
  encodeFunctionData(functionFragment: "getContract", values: [string]): string;
  encodeFunctionData(functionFragment: "isFullyPaid", values: [string]): string;
  encodeFunctionData(functionFragment: "makePayment", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerContract",
    values: [string, string, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userContracts",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFullyPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userContracts",
    data: BytesLike
  ): Result;
}

export namespace ContractCompletedEvent {
  export type InputTuple = [id: string];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRegisteredEvent {
  export type InputTuple = [
    id: string,
    initiator: AddressLike,
    counterparty: AddressLike
  ];
  export type OutputTuple = [
    id: string,
    initiator: string,
    counterparty: string
  ];
  export interface OutputObject {
    id: string;
    initiator: string;
    counterparty: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractSignedEvent {
  export type InputTuple = [id: string, signer: AddressLike];
  export type OutputTuple = [id: string, signer: string];
  export interface OutputObject {
    id: string;
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentMadeEvent {
  export type InputTuple = [
    id: string,
    payer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: string, payer: string, amount: bigint];
  export interface OutputObject {
    id: string;
    payer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContractRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ContractRegistry;
  waitForDeployment(): Promise<this>;

  interface: ContractRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contracts: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        contractHash: string;
        initiator: string;
        counterparty: string;
        initiatorAmount: bigint;
        counterpartyAmount: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
        initiatorPaid: boolean;
        counterpartyPaid: boolean;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getContract: TypedContractMethod<
    [_id: string],
    [ContractRegistry.ContractDataStructOutput],
    "view"
  >;

  isFullyPaid: TypedContractMethod<[_id: string], [boolean], "view">;

  makePayment: TypedContractMethod<[_id: string], [void], "payable">;

  registerContract: TypedContractMethod<
    [
      _id: string,
      _hash: string,
      _counterparty: AddressLike,
      _initiatorAmount: BigNumberish,
      _counterpartyAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  signContract: TypedContractMethod<[_id: string], [void], "nonpayable">;

  userContracts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        contractHash: string;
        initiator: string;
        counterparty: string;
        initiatorAmount: bigint;
        counterpartyAmount: bigint;
        initiatorSigned: boolean;
        counterpartySigned: boolean;
        initiatorPaid: boolean;
        counterpartyPaid: boolean;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContract"
  ): TypedContractMethod<
    [_id: string],
    [ContractRegistry.ContractDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isFullyPaid"
  ): TypedContractMethod<[_id: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "makePayment"
  ): TypedContractMethod<[_id: string], [void], "payable">;
  getFunction(
    nameOrSignature: "registerContract"
  ): TypedContractMethod<
    [
      _id: string,
      _hash: string,
      _counterparty: AddressLike,
      _initiatorAmount: BigNumberish,
      _counterpartyAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "signContract"
  ): TypedContractMethod<[_id: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userContracts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEvent(
    key: "ContractCompleted"
  ): TypedContractEvent<
    ContractCompletedEvent.InputTuple,
    ContractCompletedEvent.OutputTuple,
    ContractCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRegistered"
  ): TypedContractEvent<
    ContractRegisteredEvent.InputTuple,
    ContractRegisteredEvent.OutputTuple,
    ContractRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ContractSigned"
  ): TypedContractEvent<
    ContractSignedEvent.InputTuple,
    ContractSignedEvent.OutputTuple,
    ContractSignedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentMade"
  ): TypedContractEvent<
    PaymentMadeEvent.InputTuple,
    PaymentMadeEvent.OutputTuple,
    PaymentMadeEvent.OutputObject
  >;

  filters: {
    "ContractCompleted(string)": TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;
    ContractCompleted: TypedContractEvent<
      ContractCompletedEvent.InputTuple,
      ContractCompletedEvent.OutputTuple,
      ContractCompletedEvent.OutputObject
    >;

    "ContractRegistered(string,address,address)": TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;
    ContractRegistered: TypedContractEvent<
      ContractRegisteredEvent.InputTuple,
      ContractRegisteredEvent.OutputTuple,
      ContractRegisteredEvent.OutputObject
    >;

    "ContractSigned(string,address)": TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;
    ContractSigned: TypedContractEvent<
      ContractSignedEvent.InputTuple,
      ContractSignedEvent.OutputTuple,
      ContractSignedEvent.OutputObject
    >;

    "PaymentMade(string,address,uint256)": TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;
    PaymentMade: TypedContractEvent<
      PaymentMadeEvent.InputTuple,
      PaymentMadeEvent.OutputTuple,
      PaymentMadeEvent.OutputObject
    >;
  };
}
